-- DATABASE 생성
CREATE DATABASE IF NOT EXISTS DOCHI;

-- DATABASE USER 생성
---- 로컬에서만 접속 가능한 계정.
CREATE OR REPLACE USER 'dochi'@'localhost' IDENTIFIED BY 'dochi';
  -- 외부에서 접속 가능한 계정.
CREATE OR REPLACE USER 'dochi'@'%' IDENTIFIED BY 'dochi';

---- 권한 부여
GRANT ALL PRIVILEGES ON DOCHI.* TO 'dochi'@'localhost';
GRANT ALL PRIVILEGES ON DOCHI.* TO 'dochi'@'%';

---- 권한 적용
FLUSH PRIVILEGES;


-- USER TABLE 생성
CREATE TABLE DOCHI.AT_USER (
  USER_ID		    VARCHAR(50)	  NOT NULL,
  USER_PW	      VARCHAR(100)	NOT NULL,
  USER_NAME	    VARCHAR(50)	  NOT NULL,
  USER_NICK	    VARCHAR(50),
  USER_EMAIL		VARCHAR(100),
  USER_MOBILE	  VARCHAR(20),
  REG_USER	    VARCHAR(50),
  REG_DTTM	    VARCHAR(14),
  UPD_USER	    VARCHAR(50),
  UPD_DTTM	    VARCHAR(14)
);

-- USER TABLE PK 생성
ALTER TABLE DOCHI.AT_USER
  ADD CONSTRAINT PK_AT_USER
  PRIMARY KEY ( USER_ID )
;

-- AUTH TABLE 생성
CREATE TABLE DOCHI.AT_AUTH (
  AUTH_ID		VARCHAR(10),
  AUTH_NAME	VARCHAR(50),
  REG_USER	VARCHAR(50),
  REG_DTTM	VARCHAR(14),
  UPD_USER	VARCHAR(50),
  UPD_DTTM	VARCHAR(14)
);

-- AUTH TABLE PK 생성
ALTER TABLE DOCHI.AT_AUTH
  ADD CONSTRAINT PK_AT_AUTH
  PRIMARY KEY ( AUTH_ID )
;


-- USER AUTH MAPPING TABLE 생성
CREATE TABLE DOCHI.AT_USER_AUTH_MAP (
  USER_ID		VARCHAR(50)	NOT NULL,
  AUTH_ID		VARCHAR(10)	NOT NULL,
  IS_MAJOR	VARCHAR(1)	DEFAULT 'N',
  REG_USER	VARCHAR(50),
  REG_DTTM	VARCHAR(14),
  UPD_USER	VARCHAR(50),
  UPD_DTTM	VARCHAR(14)
);


-- USER AUTH MAPPING TABLE PK 생성
ALTER TABLE DOCHI.AT_USER_AUTH_MAP
  ADD CONSTRAINT PK_AT_USER_AUTH_MAP
  PRIMARY KEY ( USER_ID, AUTH_ID )
;

-- INSERT 'admin' USER DATA
INSERT INTO DOCHI.AT_USER (
  USER_ID,
  USER_PW,
  USER_NAME,
  USER_NICK,
  USER_EMAIL,
  USER_MOBILE,
  REG_USER,
  REG_DTTM
) VALUES (
  'admin',
  'admin',
  '허정운',
  '관리자',
  'dochi@dochi.com',
  '01012345678',
  'SYSTEM',
  DATE_FORMAT(SYSDATE(), '%Y%m%d%H%i%s')
);

-- INSERT 'admin' AUTH DATA
INSERT INTO DOCHI.AT_AUTH (
  AUTH_ID,
  AUTH_NAME,
  REG_USER,
  REG_DTTM
) VALUES (
  '1000',
  'administrator',
  'admin',
  DATE_FORMAT(SYSDATE(), '%Y%m%d%H%i%s')
);

-- INSERT 'admin' USER&AUTH MAPPING DATA
INSERT INTO DOCHI.AT_USER_AUTH_MAP (
  USER_ID,
  AUTH_ID,
  IS_MAJOR,
  REG_USER,
  REG_DTTM
) VALUES (
  'admin',
  '1000',
  'Y',
  'SYSTEM',
  DATE_FORMAT(SYSDATE(), '%Y%m%d%H%i%s')
);

-- UPDATE 'admin' PASSWORD TO ENCRYPTED PASSWORD
UPDATE DOCHI.AT_USER
   SET USER_PW = 'gAAAAABfZDnQlCcoUNABP31hqiJROzEwoC2JlwU7YWdLuS0gpSvvaTdTuGQFo90Ilm5Vs82mgwvIOGRIGiI3uclI8GXl6qzDDg=='
 WHERE 1=1
;

COMMIT;